#!/usr/bin/env python
"""Calculates the WER of the predictions generated by the fairseq-generate commands"""
import argparse

incorrect = 0
examples = 0
target_list = []
hypo_list = []

def main(args: argparse.Namespace) -> None:

    incorrect = 0
    examples = 0
    target_list = []
    hypo_list = []

    with open(args.predictions, "r") as source: 
        lines = source.readlines()
        for line in lines:
            if line.startswith("T-"):
                new_line = line.rstrip("\n")
                target_list.append(new_line.split("\t")[-1])
            elif line.startswith("H-"): 
                new_line = line.rstrip("\n")
                hypo_list.append(new_line.split("\t")[-1])

    for target, hypo in zip(target_list, hypo_list):
        examples += 1
        if target != hypo:
            incorrect += 1

    WER = (incorrect/examples)*100

    print(f"WER:\t{WER}%")
# Output when I ran this program on my terminal:     
# (base) Amals-Air:hw2-amalaissaoui amalaissaoui$ python Amal_HW2_LT_part4.py predictions.txt
# WER:	16.0%


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("predictions", help="path to the predictions generated by fairseq-generate")
main(parser.parse_args())